package notaSpese;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import notaSpese.Trasferta;
import notaSpese.TrasferteRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called TrasferteRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private TrasferteRepository TrasferteRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewTrasferta (@RequestParam String Nome
			, @RequestParam String DataInizio
			, @RequestParam String DataFine
			, @RequestParam String DataSpesa
			, @RequestParam String Descrizione
			, @RequestParam float Importo
			) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Trasferta t = new Trasferta();
		t.setNome(Nome);
		t.setDataInizio(DataInizio);
		t.setDataFine(DataFine);
		t.setDataSpesa(DataSpesa);
		t.setDescrizione(Descrizione);
		t.setImporto(Importo);
		TrasferteRepository.save(t);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Trasferta> getAllTrasferte() {
		// This returns a JSON or XML with the Trasferte
		return TrasferteRepository.findAll();
	}
}
